# Variable 'python.version' was defined in the Variables tab
# Multi-job configuration must be converted to matrix strategy: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-job-configuration
trigger:
  branches:
    include:
    - master
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Phase_1
  displayName: Build and Test
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: UsePythonVersion@0
    displayName: Use Python $(python.version)
    inputs:
      versionSpec: $(python.version)
  - task: CmdLine@2
    displayName: Install dependencies
    inputs:
      script: python -m pip install --upgrade pip && pip install -r requirements.txt
  - task: CmdLine@2
    displayName: Flake8
    continueOnError: True
    enabled: False
    inputs:
      script: pip install flake8 && flake8
  - task: CmdLine@2
    displayName: unittest
    inputs:
      script: python -m unittest test_camera.py > test-results.xml
  - task: PublishTestResults@2
    displayName: Publish Test Results **/test-results.xml
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: Python $(python.version)
- job: Phase_2
  displayName: Publish
  dependsOn: Phase_1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: UsePythonVersion@0
    displayName: Use Python >= 3.6
    inputs:
      versionSpec: '>= 3.6'
  - task: CmdLine@2
    displayName: Build sdist
    inputs:
      script: python setup.py sdist
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dist'
    inputs:
      PathtoPublish: dist
      ArtifactName: dist
...
